CREATE DATABASE ACC_BBALL;

CREATE TABLE PLAYER (
	PLAYER_ID integer,
	TEAM_ID integer, 
	UNIFORM_NUM integer, 
	FIRST_NAME text, 
	LAST_NAME text, 
	MPG integer, 
	PPG integer, 
	RPG integer, 
	APG integer, 
	SPG double precision, 
	BPG double precision,
	PRIMARY KEY(PLAYER_ID),
	FOREIGN KEY(TEAM_ID) REFERENCES TEAM ON UPDATE CASCADE ON DELETE SET NULL
	);

CREATE TABLE TEAM (
	TEAM_ID integer, 
	NAME text, 
	STATE_ID integer, 
	COLOR_ID integer, 
	WINS integer, 
	LOSSES integer,
	PRIMARY KEY(TEAM_ID),
	FOREIGN KEY(STATE_ID) REFERENCES STATE ON UPDATE CASCADE ON DELETE SET NULL, 
	FOREIGN KEY(COLOR_ID) REFERENCES COLOR ON UPDATE CASCADE ON DELETE SET NULL
	);

CREATE TABLE STATE (
	STATE_ID integer, 
	NAME text,
	PRIMARY KEY(STATE_ID)
	);

CREATE TABLE COLOR (
	COLOR_ID integer, 
	NAME text,
	PRIMARY KEY(COLOR_ID)
	);

INSERT INTO PLAYER VALUES  (1, 1, 1, 'Jerome', 'Robinson',4, 19, 4, 3, 1.7, 0.4);
INSERT INTO PLAYER VALUES  (2, 1, 0, 'Ky', 'Bowman', 29, 14, 5, 3, 1.2, 0.1);
INSERT INTO PLAYER VALUES  (3, 1, 25, 'Jordan', 'Chatman', 25, 9, 2, 1, 0.6, 0.2);
INSERT INTO PLAYER VALUES  (4, 1, 11, 'A.J.', 'Turner', 31, 8, 3, 3, 0.6, 0.2);
INSERT INTO PLAYER VALUES  (5, 1, 21, 'Nik', 'Popovic', 14, 6, 4, 0, 0.1, 0.3);
INSERT INTO PLAYER VALUES  (6, 1, 2, 'Connar', 'Tava', 25, 6, 5, 2, 0.7, 0.3);
INSERT INTO PLAYER VALUES  (7, 1, 15, 'Mo', 'Jeffers', 20, 6, 6, 1, 0.4, 0.5);
INSERT INTO PLAYER VALUES  (8, 1, 13, 'Ty', 'Graves', 19, 5, 1, 2, 0.0, 0.2);
INSERT INTO PLAYER VALUES  (9, 1, 23, 'Mike', 'Sagay', 5, 2, 1, 0, 0.1, 0.1);
INSERT INTO PLAYER VALUES  (10, 1, 5, 'Garland', 'Owens', 11, 2, 2, 1, 0.1, 0.2);


INSERT INTO TEAM VALUES (1, 'BostonCollege', 10, 7, 2, 16);
INSERT INTO TEAM VALUES (2, 'Clemson', 6, 2, 6, 12);
INSERT INTO TEAM VALUES (3, 'Duke', 1, 5, 11, 7);
INSERT INTO TEAM VALUES (4, 'FloridaState', 3, 7, 12, 6);
INSERT INTO TEAM VALUES (5, 'GeorgiaTech', 9, 6, 8, 10);
INSERT INTO TEAM VALUES (6, 'Louisville', 4, 4, 12, 6);
INSERT INTO TEAM VALUES (7, 'Miami', 3, 3, 10, 8);
INSERT INTO TEAM VALUES (8, 'NCSU', 1, 4, 4, 14);
INSERT INTO TEAM VALUES (9, 'NotreDame', 5, 6, 12, 6);
INSERT INTO TEAM VALUES (10,'Pittsburgh', 7, 8, 4, 14);
INSERT INTO TEAM VALUES (11, 'Syracuse', 8, 2, 10, 8);
INSERT INTO TEAM VALUES (12, 'UNC', 1, 1, 14, 4);
INSERT INTO TEAM VALUES (13, 'Virginia', 2, 2, 11, 7);
INSERT INTO TEAM VALUES (14, 'VirginiaTech', 2, 7, 10, 8);
INSERT INTO TEAM VALUES (15, 'WakeForest', 1, 6, 9 ,9);

1 SELECT * FROM PLAYER WHERE MPG >= 35 AND MPG <= 40;

2 SELECT TEAM.NAME 
	FROM TEAM
	INNER JOIN COLOR
	ON TEAM.COLOR_ID = COLOR.COLOR_ID
	WHERE COLOR.NAME = 'Red';

3 SELECT PLAYER.FIRST_NAME, PLAYER.LAST_NAME
	FROM PLAYER
	INNER JOIN TEAM
	ON PLAYER.TEAM_ID = TEAM.TEAM_ID
	WHERE TEAM.NAME = 'BostonCollege'
	ORDER BY PLAYER.PPG DESC;

4 SELECT PLAYER.FIRST_NAME, PLAYER.LAST_NAME, PLAYER.PLAYER_ID
	FROM PLAYER
	INNER JOIN TEAM
	ON PLAYER.TEAM_ID = TEAM.TEAM_ID
	INNER JOIN STATE
	ON TEAM.STATE_ID = STATE.STATE_ID
	INNER JOIN COLOR
	ON TEAM.COLOR_ID = COLOR.COLOR_ID
	WHERE STATE.NAME = 'MA' AND COLOR.NAME = 'Maroon';

5 SELECT PLAYER.FIRST_NAME, PLAYER.LAST_NAME, TEAM.NAME, TEAM.WINS
	FROM PLAYER
	INNER JOIN TEAM
	ON PLAYER.TEAM_ID = TEAM.TEAM_ID
	WHERE TEAM.WINS > 1;










